spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-9zelcs0o.sql.tencentcdb.com:26322/vue_db?useSSL=false&&useUnicode=true&characterEncoding=UTF-8
    username: Clover614
    password: Clover614
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connection-timeout: 30000 #连接超时时间
    validation-timeout: 30000 #连接检验超时时间
    max-lifetime: 14400 #连接最大存活时间
    maximum-pool-size: 10 #最大连接数  

logging:
  level:
    tacos: WARN

server:
  port: 9000
